export const ServerResponseCode = {
  // SPECIFIC ERROR CODES
  JOB_WITH_SAME_NAME_EXIST: 501,
  JOB_NAME_NOT_PRESENT: 502,

  JOB_ALREADY_IN_RUNNING_STATE: 510,

  JOB_NOT_IN_PAUSED_STATE: 520,
  JOB_NOT_IN_RUNNING_STATE: 521,

  JOB_DOESNT_EXIST: 500,

  // GENERIC ERROR
  ERROR: 400,

  EmailExist: 302,

  CREATED: 201,

  // SUCCESS CODES
  SUCCESS: 200,

  // TIME_OUT: 600,

  FORBIDDEN: 403,

  UNAUTHORIZED: 401
};
